name: ci

on:
  push:
  pull_request:
  release:
    types:
      - published

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    env:
      vcpkg-tag: "2022.01.01"
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: macOS - Set ENV variables for clang 13
        if: matrix.os == 'macos-latest'
        run: |
          echo "CC=$(brew --prefix llvm)/bin/clang" >> $GITHUB_ENV
          echo "CXX=$(brew --prefix llvm)/bin/clang++" >> $GITHUB_ENV

      - name: macOS - Check clang version
        if: matrix.os == 'macos-latest'
        run: $CC --version

      - name: macOS|windows - cache vcpkg
        if: matrix.os == 'macos-latest' || matrix.os == 'windows-latest'
        uses: actions/cache@v2
        env:
          cache-name: cache-vcpgk
        with:
          path: |
            ${{ github.workspace }}/vcpkg
            ${{ github.workspace }}/build/vcpkg_installed
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ env.vcpkg-tag }}-${{ hashFiles('vcpkg.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-${{ env.vcpkg-tag }}
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: macOS|windows - download vcpkg
        if: (matrix.os == 'macos-latest' || matrix.os == 'windows-latest') && steps.cache-vcpkg.outputs.cache-hit != 'true'
        run: |
          git clone https://github.com/microsoft/vcpkg ${{ github.workspace }}/vcpkg
          pushd vcpkg
          git checkout --force ${{ env.vcpkg-tag }}
          popd

      - name: macOS - bootstrap vcpkg
        if: matrix.os == 'macos-latest' && steps.cache-vcpkg.outputs.cache-hit != 'true'
        run: vcpkg/bootstrap-vcpkg.sh

      - name: windows - bootstrap vcpkg
        if: matrix.os == 'windows-latest' && steps.cache-vcpkg.outputs.cache-hit != 'true'
        run: vcpkg/bootstrap-vcpkg.bat

      - name: all - build wheels
        env:
          VCPKG_ROOT: vcpkg/
        uses: pypa/cibuildwheel@v2.3.1

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build sdist
        run: pipx run build --sdist

      - uses: actions/upload-artifact@v2
        with:
          path: dist/*.tar.gz

  upload_pypi:
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: artifact
          path: dist

      - uses: pypa/gh-action-pypi-publish@v1.4.2
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}
          # To test: repository_url: https://test.pypi.org/legacy/
