name: "docs"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types:
      - published
jobs:
  build_docs:
    name: Build docs
    runs-on: ubuntu-latest
    env:
      VCPKG_ROOT: vcpkg/
      vcpkg-tag: "2022.03.10"
      VCPKG_DEFAULT_BINARY_CACHE: "${{ github.workspace }}/vcpkg/.cache"

    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install gcc-11
        run: |
          sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
          sudo apt update
          sudo apt install gcc-11 g++-11 ninja-build
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 110 --slave /usr/bin/g++ g++ /usr/bin/g++-11 --slave /usr/bin/gcov gcov /usr/bin/gcov-11

      - name: download vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg ${{ github.workspace }}/vcpkg || true
          pushd vcpkg
          mkdir -p .cache
          git checkout --force ${{ env.vcpkg-tag }}
          ./bootstrap-vcpkg.sh
          popd

      - name: Build pynwn
        run: |
          cmake --preset=linux
          cmake --build --preset default

      - name: Build docs
        run: |
          pushd ${{ github.workspace }}/docs
          python -m pip install -r requirements.txt
          make html
          popd

      - name: deploy docs to github pages
        if: github.event_name == 'push'
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: "${{ github.workspace }}/docs/_build/html"
          clean: true
